CentOS_web_db/mycodey/mycodey/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views

urlpatterns = [
    path('', views.index),
    path('', include('django.contrib.auth.urls')),
    path('join/', views.userJoin),
    path('board/', views.boardIndex),
    path('board/write/', views.boardWrite),
    path('board/update/<int:board_id>/', views.boardUpdate),
    path('board/delete/<int:board_id>/', views.boardDelete),
    path('board/view/<int:board_id>/', views.boardView),
    path('board/good_bad/<int:board_id>/', views.boardGoodBad),
    path('admin/', admin.site.urls),
]

CentOS_web_db/mycodey/mycodey/models.py
from django.db import models

class Board(models.Model):
    title = models.CharField(max_length=250)
    author = models.CharField(max_length=50)
    content = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    view_cnt = models.IntegerField(default=0)
    good_cnt = models.IntegerField(default=0)
    bad_cnt = models.IntegerField(default=0)

CentOS_web_db/mycodey/mycodey/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import HttpResponse
from django.contrib.auth.models import User
from .models import Board

def index(request):
    return render(request, 'index.html')

def userJoin(request):
    if request.method == 'GET':
        return render(request, 'registration/join.html')
    elif request.method == 'POST':
        # 회원가입에 필요한 최소 정보 | 추가 정보
        # 계정명, 패스워드            | 이메일, 성, 이름
        user_exists = User.objects.filter(username=request.POST.get('username')).count()
        pass_check = 0
        if user_exists == 0:
            if request.POST.get('password') == request.POST.get('pass_chk'):
                data = User.objects.create_user(
                    request.POST.get('username'),
                    request.POST.get('email'),
                    request.POST.get('password'),
                    first_name=request.POST.get('first_name'),
                    last_name=request.POST.get('last_name')
                )
                return redirect('/')
            pass_check = 1

        # 패스워드 체크에 문제가 있을 때 및 기존에 가입된 사용자가 있을 때
        context = {
            'data': request.POST,
            'user_exists': user_exists,
            'pass_check': pass_check
        }
        return render(request, 'registration/join.html', context)

def boardIndex(request):
    data = Board.objects.all().order_by('-id')  # id를 기준으로 역순 정렬
    context = {
        'data': data
    }
    return render(request, 'board/index.html', context)

def boardWrite(request):
    if request.user.is_authenticated:
        if request.method == 'GET':
            return render(request, 'board/write.html')
        elif request.method == 'POST':
            data = Board()
            data.title = request.POST.get('title')
            data.content = request.POST.get('content')
            data.author = request.user.username
            data.save()

            return redirect(f'/board/view/{data.id}/')
    else:
        return redirect('/login/')

def boardUpdate(request, board_id):
    if request.user.is_authenticated:
        data = Board.objects.get(id=board_id)
        if request.user.username == data.author:
            if request.method == 'GET':
                context = {
                    'data': data
                }
                return render(request, 'board/update.html', context)
            elif request.method == 'POST':
                data.title = request.POST.get('title')
                data.content = request.POST.get('content')
                data.save()
                return redirect(f'/board/view/{data.id}/')
        else:
            # return redirect('/error/permission/')
            return HttpResponse('수정 할 권한이 없습니다.')
    else:
        return redirect('/login/')

def boardDelete(request, board_id):
    if request.user.is_authenticated:
        data = Board.objects.get(id=board_id)
        if request.user.username == data.author:
            if request.method == 'GET':
                context = {
                    'data': data
                }
                return render(request, 'board/delete.html', context)
            elif request.method == 'POST':
                data.delete()
                return redirect('/board/')
        else:
            # return redirect('/error/permission/')
            return HttpResponse('삭제할 권한이 없습니다.')
    else:
        return redirect('/login/')

def boardView(request, board_id):
    data = Board.objects.get(id=board_id)

    if not request.COOKIES.get('view'):
        data.view_cnt += 1
        data.save(update_fields=('view_cnt',))

    context = {
        'data': data
    }

    response = render(request, 'board/view.html', context)
    response.set_cookie('view', True, max_age=60*60*24*14, path=f'/board/view/{data.id}/')
    return response

def boardGoodBad(request, board_id):
    if request.user.is_authenticated:
        data = Board.objects.get(id=board_id)
        
        if not request.COOKIES.get('good_bad'):
            if request.GET.get('flag') == 'good':
                data.good_cnt += 1
                data.save(update_fields=('good_cnt',))
            elif request.GET.get('flag') == 'bad':
                data.bad_cnt += 1
                data.save(update_fields=('bad_cnt',))

        response = redirect(f'/board/view/{data.id}')
        response.set_cookie('good_bad', True, max_age=60*60*24*14, path=f'/board/good_bad/{data.id}/')
        return response
    else:
        return redirect('/login/')

CentOS_web_db/mycodey/mycodey/templates/board/delete.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>myCodey 삭제</title>
    <link rel="stylesheet" href="/static/bootstrap-4.5.2/css/bootstrap.min.css">
    <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="/static/bootstrap-4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">myCodey</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMenu" aria-controls="navbarMenu" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarMenu">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/board/">게시판</a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/login/">로그인</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/join/">가입</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <section class="container mt-3">
        <p>{{ data.title }}</p>
        <p>삭제할 자료가 맞습니까?</p>
        <form action="/board/delete/{{ data.id }}/" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <button class="btn btn-primary" type="submit">확인</button>
                <button class="btn btn-danger" type="button" onclick="location.href='/board/view/{{ data.id }}/'">취소</button>
            </div>
        </form>
    </section>
</body>
</html>

CentOS_web_db/mycodey/mycodey/templates/board/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>myCodey 게시판</title>
    <link rel="stylesheet" href="/static/bootstrap-4.5.2/css/bootstrap.min.css">
    <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="/static/bootstrap-4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">myCodey</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMenu" aria-controls="navbarMenu" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarMenu">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/board/">게시판</a>
                    </li>
                </ul>
                {% if user.is_authenticated %}
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <span class="nav-link">{{ user.username }}</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/logout/">로그아웃</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">내정보</a>
                        </li>
                    </ul>
                {% else %}
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="/login/">로그인</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/join/">가입</a>
                        </li>
                    </ul>
                {% endif %}
            </div>
        </nav>
    </header>
    <section class="container">
        {% if user.is_authenticated %}
            <div>
                <button class="btn btn-light" type="button" onclick="location.href='/board/write/'">글쓰기</button>
            </div>
        {% endif %}
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">번호</th>
                    <th scope="col">제목</th>
                    <th scope="col">작성자</th>
                    <th scope="col">조회수</th>
                    <th scope="col">작성일</th>
                    <th scope="col">추천</th>
                </tr>
            </thead>
            <tbody>
                {% for d in data %}
                    <tr>
                        <td scope="col">{{ d.id }}</td>
                        <td scope="col"><a href="/board/view/{{ d.id }}/">{{ d.title }}</a></td>
                        <td scope="col">{{ d.author }}</td>
                        <td scope="col">{{ d.view_cnt }}</td>
                        <td scope="col">{{ d.create_date|date:'Y-m-d' }}</td>
                        <td scope="col">{{ d.good_cnt }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div></div>
    </section>
</body>
</html>

CentOS_web_db/mycodey/mycodey/templates/board/update.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>myCodey 수정</title>
    <link rel="stylesheet" href="/static/bootstrap-4.5.2/css/bootstrap.min.css">
    <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="/static/bootstrap-4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">myCodey</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMenu" aria-controls="navbarMenu" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarMenu">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/board/">게시판</a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/login/">로그인</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/join/">가입</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <section class="container mt-3">
        <form action="/board/update/{{ data.id }}/" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_title">제목</label>
                <input class="form-control" id="id_title" type="text" name="title" value="{{ data.title }}">
            </div>
            <div class="form-group">
                <label for="id_content">내용</label>
                <textarea class="form-control" id="id_content" name="content" cols="30" rows="10">{% autoescape off %}{{ data.content }}{% endautoescape %}</textarea>
            </div>
            <div class="form-group">
                <button class="btn btn-primary btn-block" type="submit">저장</button>
            </div>
        </form>
    </section>
</body>
</html>

CentOS_web_db/mycodey/mycodey/templates/board/view.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>myCodey 게시글 보기</title>
    <link rel="stylesheet" href="/static/bootstrap-4.5.2/css/bootstrap.min.css">
    <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="/static/bootstrap-4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">myCodey</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMenu" aria-controls="navbarMenu" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarMenu">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/board/">게시판</a>
                    </li>
                </ul>
                {% if user.is_authenticated %}
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <span class="nav-link">{{ user.username }}</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/logout/">로그아웃</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">내정보</a>
                        </li>
                    </ul>
                {% else %}
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="/login/">로그인</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/join/">가입</a>
                        </li>
                    </ul>
                {% endif %}
            </div>
        </nav>
    </header>
    <section class="container mt-3">
        <div class="card border-light">
            <div class="card-header">
                <small>번 호 : {{ data.id }}</small><br>
                <small>작성자 : {{ data.author }}</small><br>
                <small>생성일 : {{ data.create_date|date:'Y년 m월 d일 H시 i분 s초' }}</small><br>
                <small>수정일 : {{ data.update_date|date:'Y년 m월 d일 H시 i분 s초' }}</small><br>
                <h1 class="display-4 mt-3">{{ data.title }}</h1>
            </div>
            <div class="card-body">
                <p class="card-text">{{ data.content|linebreaksbr }}</p>
                <div class="form-group">
                    <button class="btn btn-outline-success" onclick="location.href='/board/good_bad/{{ data.id }}/?flag=good'">추천 <span class="badge badge-light">{{ data.good_cnt }}</span></button>
                    <button class="btn btn-outline-danger" onclick="location.href='/board/good_bad/{{ data.id }}/?flag=bad'">비추천 <span class="badge badge-light">{{ data.bad_cnt }}</span></button>
                </div>
            </div>
            <div class="card-footer">
                <div class="form-group mt-3">
                    <button class="btn btn-info" type="button" onclick="location.href='/board/'">목록</button>
                    {% if user.username == data.author %}
                        <button class="btn btn-primary" type="button" onclick="location.href='/board/update/{{ data.id }}/'">수정</button>
                        <button class="btn btn-danger" type="button" onclick="location.href='/board/delete/{{ data.id }}/'">삭제</button>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
</body>
</html>

CentOS_web_db/mycodey/mycodey/templates/board/write.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>myCodey 글쓰기</title>
    <link rel="stylesheet" href="/static/bootstrap-4.5.2/css/bootstrap.min.css">
    <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="/static/bootstrap-4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">myCodey</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMenu" aria-controls="navbarMenu" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarMenu">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/board/">게시판</a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/login/">로그인</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/join/">가입</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <section class="container mt-3">
        <form action="/board/write/" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_title">제목</label>
                <input class="form-control" id="id_title" type="text" name="title">
            </div>
            <div class="form-group">
                <label for="id_content">내용</label>
                <textarea class="form-control" id="id_content" name="content" cols="30" rows="10"></textarea>
            </div>
            <div class="form-group">
                <button class="btn btn-primary btn-block" type="submit">저장</button>
            </div>
        </form>
    </section>
</body>
</html>

CentOS_web_db/mycodey/mycodey/templates/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>myCodey</title>
    <link rel="stylesheet" href="/static/bootstrap-4.5.2/css/bootstrap.min.css">
    <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="/static/bootstrap-4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">myCodey</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMenu" aria-controls="navbarMenu" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarMenu">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/board/">게시판</a>
                    </li>
                </ul>
                {% if user.is_authenticated %}
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <span class="nav-link">{{ user.username }}</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/logout/">로그아웃</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">내정보</a>
                        </li>
                    </ul>
                {% else %}
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="/login/">로그인</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/join/">가입</a>
                        </li>
                    </ul>
                {% endif %}
            </div>
        </nav>
    </header>
    <section>
        <article>
            <ol>
                <li>메인 페이지 HTML/CSS 적용하여 만들기</li>
                <ul>
                    <li>상단 또는 왼쪽, 오른쪽에 메뉴(네비게이션)</li>
                </ul>
                <li>게시판 페이지 HTML/CSS 적용하여 만들기</li>
                <ul>
                    <li>글쓰기 버튼</li>
                    <li>검색 기능</li>
                </ul>
            </ol>
        </article>
    </section>
</body>
</html>